/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/Navbar.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    copy: typeof import('./components/AppFooter copy.vue')['default']
    HoverMenu: typeof import('./components/HoverMenu.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavbarScorll: typeof import('./components/NavbarScorll.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
