/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/About2': RouteRecordInfo<'/About2', '/About2', Record<never, never>, Record<never, never>>,
    '/DeliveryAndReturnPolicy': RouteRecordInfo<'/DeliveryAndReturnPolicy', '/DeliveryAndReturnPolicy', Record<never, never>, Record<never, never>>,
    '/FeaturedCategories': RouteRecordInfo<'/FeaturedCategories', '/FeaturedCategories', Record<never, never>, Record<never, never>>,
    '/FeedBack': RouteRecordInfo<'/FeedBack', '/FeedBack', Record<never, never>, Record<never, never>>,
    '/HoverGallery': RouteRecordInfo<'/HoverGallery', '/HoverGallery', Record<never, never>, Record<never, never>>,
    '/ImageUpDown': RouteRecordInfo<'/ImageUpDown', '/ImageUpDown', Record<never, never>, Record<never, never>>,
    '/paralax': RouteRecordInfo<'/paralax', '/paralax', Record<never, never>, Record<never, never>>,
    '/Product': RouteRecordInfo<'/Product', '/Product', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
  }
}
